### PR TITLE
Resolve PWA installation errors in site.webmanifset

### PR DESCRIPTION
**Pull request by SN3-K**
**site.webmanifest**

- Fixed Application Scope
- Fixed Application start_url
- Added Screenshots

During this commit I also added a new folder:
packages/assets/pwa

in this folder I added a wide form factor screenshot as well as a smaller screenshot for the Rich PWA Requirements

As a result of these changes, the PWA is now installable

Tested on Ubuntu 22.04 LTS

### CODE REVIEW

**Comment by Prozilla** [comment]
> During this commit I also added a new folder:
packages/assets/pwa

I think you meant: packages/demo/public/assets/screenshots/pwa

**Comment by Prozilla** [comment]
Just reviewed the code changes and everything looks good, now just need to validate whether the issue is actually resolved.

**Comment by Prozilla** [comment]
PWA installation guide - MDN Web Docs: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#installation_from_the_web

**Comment by SN3-K** [comment]
> > During this commit I also added a new folder:
> > packages/assets/pwa
> 
> I think you meant: packages/demo/public/assets/screenshots/pwa

Ahh you would be right haha.

**Pull request merged**
